import unittest
from typing import Any
from unittest.mock import patch, mock_open, ANY
from logic import (
    read_database, create_users, encrypt, decrypt, encrypt_users, 
    export_encrypted_users, read_json_database,
      decrypt_users, export_decrypted_users)

DUMMY_JSON = "dummy_database.json"
DECRYPTED_JSON = "decrypted_database.json"

class TestProcessingData(unittest.TestCase):
    """Battery of unit tests for data reading and transforming functions"""


    def test_read_database(self) ->None:
        """Ensures that the function captures the error in case of the file not existing in the disk"""
        with self.assertRaises(FileNotFoundError):
            read_database("inexistent_file.txt") 

    @patch("builtins.open", new_callable=mock_open, read_data="Ana\nJoão")
    def test_read_database_success(self, mock_file : Any) ->None:
        """
        Simulates reading a file in memory to avoid writing to the hard drive.
        
        :param mock_file: The mocked object generated by the @patch decorator that replaces the native open() function.
        :return: None
        """
        lines = read_database("dummy.txt")
        self.assertEqual(lines, ["Ana", "João"])

    def test_create_users_empty_list(self) -> None:
        """Verifies if receiving an empty list return an empty list"""
        self.assertEqual(create_users([]), [])


    def test_create_users_id_range(self) -> None:
        """Applies the 'Range' boundary condition to ensure 9-digit"""
        users = create_users(["Ana"])
        self.assertIsInstance(users[0]["id"], int)
        self.assertTrue(100000000 <= users[0]["id"] <= 999999999)

    def test_create_users_unique_ids(self) -> None:
        """Ensures that no IDs are repeated in the generated list."""
        users = create_users(["Ana", "João", "Maria", "Pedro"])
        
        # We extract only the IDs from the dictionaries into a new list
        ids = [user["id"] for user in users]
        
        # If the length of the list is equal to the length of the set, all IDs are unique.
        self.assertEqual(len(ids), len(set(ids)))

    def test_create_users_error_type(self) -> None:
        """Ensures that passing None to the function raises a TypeError."""
        with self.assertRaises(TypeError):
            create_users(None)#NOSONAR


class TestEncrypt(unittest.TestCase):
    """Battery of unit tests to validate the mathemathical logic of encrypting"""


    def test_encrypt_simple_case(self) -> None:
        """Tests basic math of figures with a list of keys of an element"""
        self.assertEqual(encrypt("A", [3]), "D")
        self.assertEqual(encrypt("A", [1]), "B")
        self.assertEqual(encrypt("A", [4]), "E")
        self.assertEqual(encrypt("AAA", [3,1,4]), "DBE")

    def test_encrypt_empty_key(self) -> None:
        """Ensures that a list of empty keys is blocked and isn't divided by zeros"""
        with self.assertRaises(ValueError):
            encrypt("Secret", [])
    
    def test_encrypt_empty_text(self) -> None:
        """Ensures that the functions manages empty texts without collapsing"""
        self.assertEqual(encrypt("", [1]), "")

    def test_encrypt_error_type(self) -> None:
        """Ensures that the injections of invalid data types are blocked"""
        with self.assertRaises(TypeError):
            encrypt("Text", None)#NOSONAR


class TestDecrypt(unittest.TestCase):
    """Battery of unit tests to validate the mathemathical logic of decrypting"""


    def test_decrypt_simple_case(self) ->None:
        """Tests basic math of figures with a list of keys of an element"""
        self.assertEqual(decrypt("DBE", [3,1,4]), "AAA")
        self.assertEqual(decrypt("D", [3]), "A")
        self.assertEqual(decrypt("B", [1]), "A")
        self.assertEqual(decrypt("E", [4]), "A")
    
    def test_decrypt_empty_key(self) ->None:
        """Ensures that a list of empty keys is blocked and isn't divided by zeros"""
        with self.assertRaises(ValueError):
            decrypt("Secret", [])
    def test_decrypt_empty_text(self) ->None:
        """Ensures that the functions manages empty texts without collapsing"""
        self.assertEqual(decrypt("", [1]), "")

    def test_decrypt_error_type(self) ->None:
        """Ensures that the injections of invalid data types are blocked"""
        with self.assertRaises(TypeError):
            decrypt("Text", None)#NOSONAR
    

class TestEncryptUsers(unittest.TestCase):
    """Battery of unit tests to validate the encryption of user IDs in the database."""
    def test_encrypt_users_logic_and_integrity(self) -> None:
        """
        Ensures that ONLY the ID is encrypted and the name remains untouched.
        :param self: The instance of the test case object.
        :return: None.
        :raises AssertionError: If the user's name is modified or if the ID is incorrectly encrypted.
        """
      
        fake_users = [{"name": "Ana", "id": 123}]  
        keys = [1] 
        result = encrypt_users(fake_users, keys)
        self.assertEqual(result[0]["name"], "Ana")
        self.assertEqual(result[0]["id"], "234")

    def test_encrypt_users_error_type(self) -> None:
        """Ensures that invalid data types (like None) are blocked."""
        with self.assertRaises(TypeError):
            encrypt_users(None, [1])#NOSONAR

    def test_encrypt_users_empty_list(self) -> None:
        """Ensures an empty list is handled correctly."""
        self.assertEqual(encrypt_users([], [1]), [])


class TestExportUsersJSON(unittest.TestCase):
    """Battery of unit tests to validate the JSON export function."""

    def test_export_json_error_type(self) -> None:
        """Ensures that invalid data types (like None) are blocked before writing."""
        with self.assertRaises(TypeError):
            export_encrypted_users(None, DUMMY_JSON)#NOSONAR

    @patch("builtins.open", new_callable=mock_open)
    @patch("json.dump")
    def test_export_json_success(self, mock_json_dump: Any, mock_file: Any) -> None:
        """Simulates writing to a file in memory to verify correct behavior without touching the real hard drive."""
        fake_database = [{"name": "Ana", "id": "234"}]
        
        # Call the function
        export_encrypted_users(fake_database, DUMMY_JSON)
        
        # 1. Verifies if open() was called with "w" (write) mode
        mock_file.assert_called_once_with(DUMMY_JSON, "w", encoding="utf-8")
        
        # 2. Verifies if json.dump() was called to format the list into the file
        mock_json_dump.assert_called_once_with(fake_database, ANY, indent=4)

    @patch("builtins.open")
    def test_export_json_io_error(self, mock_file: Any) -> None:
        """Forces an OS Error to check if the system handles file writing failures properly."""
        # We program the mock to explode with an OSError when someone tries to open it
        mock_file.side_effect = OSError("Simulated Disk Error: No space left on device")
        
        # We ensure our function lets the OSError bubble up properly
        with self.assertRaises(OSError):
            export_encrypted_users([{"name": "Ana", "id": "234"}], "dummy_database.json")


class TestReadJsonDatabase(unittest.TestCase):
    """Battery of unit tests to validate the JSON import function."""

    def test_read_json_error_type(self) -> None:
        """Ensures that invalid data types (like None) are blocked."""
        with self.assertRaises(TypeError):
            read_json_database(None)#NOSONAR

    @patch("builtins.open", new_callable=mock_open, read_data='[{"name": "Ana", "id": "234"}]')
    def test_read_json_success(self, mock_file: Any) -> None:
        """Simulates reading a valid JSON file in memory."""
        result = read_json_database("dummy.json")
        
        # Ensures the mock file was opened in read mode
        mock_file.assert_called_once_with("dummy.json", "r", encoding="utf-8")
        
        # Ensures the JSON was correctly parsed back into a Python list of dictionaries
        self.assertEqual(len(result), 1)
        self.assertEqual(result[0]["name"], "Ana")
        self.assertEqual(result[0]["id"], "234")


class TestDecryptUsers(unittest.TestCase):
    """Battery of unit tests to validate the decryption of user IDs in the database."""

    def test_decrypt_users_logic_and_integrity(self) -> None:
        """
        Ensures that ONLY the ID is decrypted, cast to int, and the name remains untouched.
        """
        # Inject a fake user with a cyphered ID
        fake_users = [{"name": "Ana", "id": "234"}]
        
        keys = [1] 
    
        result = decrypt_users(fake_users, keys)
        self.assertEqual(result[0]["name"], "Ana")
        self.assertEqual(result[0]["id"], 123)

    def test_decrypt_users_error_type(self) -> None:
        """Ensures that invalid data types (like None) are blocked."""
        with self.assertRaises(TypeError):
            decrypt_users(None, [1])#NOSONAR

    def test_decrypt_users_empty_list(self) -> None:
        """Ensures an empty list is handled correctly."""
        self.assertEqual(decrypt_users([], [1]), [])


class TestExportDecryptedUsers(unittest.TestCase):
    """Battery of unit tests to validate the JSON export of decrypted users."""

    def test_export_decrypted_error_type(self) -> None:
        """Ensures that invalid data types (like None) are blocked before writing."""
        with self.assertRaises(TypeError):
            export_decrypted_users(None, DECRYPTED_JSON) #NOSONAR

    @patch("builtins.open", new_callable=mock_open)
    @patch("json.dump")
    def test_export_decrypted_success(self, mock_json_dump: Any, mock_file: Any) -> None:
        """Simulates writing to a file in memory to verify correct behavior."""
        fake_database = [{"name": "Ana", "id": 123}] 
        export_decrypted_users(fake_database, DECRYPTED_JSON)
        mock_file.assert_called_once_with(DECRYPTED_JSON, "w", encoding="utf-8")
        mock_json_dump.assert_called_once_with(fake_database, ANY, indent=4)

    @patch("builtins.open")
    def test_export_decrypted_io_error(self, mock_file: Any) -> None:
        """Forces an OS Error to check system handling."""
        mock_file.side_effect = OSError("Simulated Disk Error: No space left on device")
        with self.assertRaises(OSError):
            export_decrypted_users([{"name": "Ana", "id": 123}], "decrypted_databse.json")


class TestEncryptDecryptIntegration(unittest.TestCase):
    """
    Integration test to validate the full encrypt → decrypt pipeline,
    mirroring the exact flow used in main.py.
    """

    def test_roundtrip_full_user_pipeline(self) -> None:
        """
        Simulates the complete pipeline used in the main program:
        encrypts user IDs and then decrypts them, verifying the
        final data matches the original.
        """
        original_users = [
            {"name": "Ana",   "id": 123456789},
            {"name": "João",  "id": 987654321},
            {"name": "Maria", "id": 555000111},
        ]
        keys = [3, 7, 2]

        encrypted = encrypt_users(original_users, keys)
        recovered = decrypt_users(encrypted, keys)

        self.assertEqual(recovered, original_users)

if __name__ == "__main__":
    unittest.main()